[package]
name = "rustmine"
version = "0.0.2"
edition = "2024"

[dependencies]
winit = "0.30.13"
wgpu = "30.0.1"

# UI
egui = "0.36.1"
egui-winit = "0.36.1"
egui-wgpu = "0.36.1"

anyhow = "1.0.102"
env_logger = "0.11.10"
log = "0.4.29"
pollster = "1.0.1"
bytemuck = { version = "1.25.0", features = ["derive"] }
cgmath = { version = "0.18.0", features = ["serde"] }
tobj = { version = "4.0.5", default-features = false, features = ["tokio"] }
noise = "0.9.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
postcard = { version = "1.1.3", features = ["alloc"] }
dirs = "6.0.0"
image = "0.25.10"
rand = "0.10.1"
chrono = "0.4.45"
zstd = "0.13.3"
crossbeam = "0.8.4"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "rustls"] }
wiremock = "0.6.5"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
itertools = "0.15.0"
