name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test-build release artifacts
    uses: ./.github/workflows/workflow-build.yaml
    permissions:
      contents: read
    secrets: inherit

  check:
    name: Check code style
    uses: ./.github/workflows/workflow-check.yaml
    permissions:
      contents: read
    secrets: inherit
