name: Check release

on:
  pull_request:
    branches:
      - release

jobs:
  check-version:
    name: Check next release version
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get release version
        uses: wemogy/get-release-version-action@v4.3.3
        id: get-release-version
        with:
          create-tag: false

      - name: Fail on missing changes
        if: steps.get-release-version.outputs.tag-created != 'true'
        run: |
          exit 1
