name: Check release

on:
  pull_request:
    branches:
      - release

jobs:
  check-version:
    name: Check next release version
    uses: ./.github/workflows/workflow-get-version.yaml
    permissions:
      contents: read
