name: Release

on:
  push:
    branches:
      - release

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  get-version:
    name: Get next release version
    uses: ./.github/workflows/workflow-get-version.yaml
    permissions:
      contents: read

  build:
    name: Build release artifacts
    uses: ./.github/workflows/workflow-build.yaml
    needs:
      - get-version
    permissions:
      contents: read
    with:
      version: ${{ needs.get-version.outputs.version }}
      publish: true

  release:
    name: Publish release artifacts
    uses: ./.github/workflows/workflow-release.yaml
    needs:
      - get-version
      - build
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    with:
      version: ${{ needs.get-version.outputs.version }}
      version-number: ${{ needs.get-version.outputs.version-number }}
