name: Publish release artifacts

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: v0.0.0
        description: The release version, in the format of v0.0.0
      version-number:
        type: string
        default: 0.0.0
        description: The release version without the prefix, in the format of 0.0.0

jobs:
  publish-authentication-service:
    name: Publish RustMine Authentication Service
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Download docker image artifact
        uses: actions/download-artifact@v8
        with:
          name: authentication-service-image
          path: ${{ runner.temp }}

      - name: Load docker image
        run: |
          docker load --input ${{ runner.temp }}/authentication-service.tar

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push docker image
        run: |
          docker image push --all-tags ghcr.io/bennetrr/rustmine-authentication-service

  deploy-docs:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: release-binary*
          merge-multiple: true
          path: release-binaries

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: RustMine ${{ inputs.version-number }}
          tag: ${{ inputs.version }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
          artifacts: release-binaries/*
