name: Build release artifacts

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: v0.0.0
        description: The release version, in the format of v0.0.0
      publish:
        type: boolean
        default: false
        description: Whether to upload build artifacts

jobs:
  rustmine:
    name: Build RustMine
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: ${{ inputs.publish }}
      matrix:
        include:
          - rust_target: x86_64-unknown-linux-gnu
            binary_name: rustmine-${{ inputs.version }}-linux-amd64
            os: ubuntu-latest
          - rust_target: x86_64-pc-windows-msvc
            binary_name: rustmine-${{ inputs.version }}-windows-amd64.exe
            os: windows-latest
          - rust_target: aarch64-apple-darwin
            binary_name: rustmine-${{ inputs.version }}-macos-arm64
            os: macos-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@1.97.1
        with:
          target: ${{ matrix.rust_target }}

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2.9.1

      - name: Build release binary
        run: |
          cargo build --release --bin rustmine --target ${{ matrix.rust_target }}

      - name: Move release binary
        if: inputs.publish
        shell: bash
        run: |
          if [[ "${{ matrix.binary_name }}" == *.exe ]]; then
            mv target/${{ matrix.rust_target }}/release/rustmine.exe ${{ matrix.binary_name }}
          else
            mv target/${{ matrix.rust_target }}/release/rustmine ${{ matrix.binary_name }}
          fi

      - name: Upload release artifacts
        if: inputs.publish
        uses: actions/upload-artifact@v7
        with:
          name: release-binary-${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}
          if-no-files-found: error

  rustmine-authentication-service:
    name: Build RustMine Authentication Service
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v4

      - name: Build image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/bennetrr/rustmine-authentication-service
          flavor: |
            latest=true
          tags: |
            type=sha,prefix=
            type=semver,pattern={{version}},value=${{ inputs.version }}

      - name: Build docker image
        uses: docker/build-push-action@v7
        with:
          file: rustmine-authentication-service/docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/authentication-service.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload docker image artifact
        if: inputs.publish
        uses: actions/upload-artifact@v7
        with:
          name: authentication-service-image
          path: ${{ runner.temp }}/authentication-service.tar
          if-no-files-found: error

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Set up node
        uses: pnpm/setup@v1.0.0
        with:
          package-json-file: docs/package.json
          runtime: node@26
          cache: true
          cache-dependency-path: docs/pnpm-lock.yaml
          install: false

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
        working-directory: docs

      - name: Build documentation
        run: |
          pnpm build
        working-directory: docs

      - name: Upload Pages artifact
        if: inputs.publish
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/dist

# TODO:
# - cargo doc --no-deps
# - cargo modules dependencies --package $TARGET --bin $TARGET --no-uses --no-externs --verbose > dependencies.dot
# - cargo modules structure --package $TARGET --bin $TARGET --verbose --cfg-test | sed -r 's/\x1B\[(;?[0-9]{1,3})+[mGK]//g' > structure.txt
# -> Include in published documentation?
